import Head from 'next/head';
import { useState } from 'react';
import { Inter } from 'next/font/google';
import { GasModal } from '@/features/gas';
import { Layout } from '@/components/containers';
import { PrimaryButton } from '@/components/elements';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [openModal, setOpenModal] = useState<boolean>(false);

  const handleClose = () => {
    setOpenModal(false);
  };

  const handleOpen = () => {
    setOpenModal(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Layout>
          <PrimaryButton text="Open" handleClick={handleOpen} />
        </Layout>
      </>
      <GasModal handleClose={handleClose} openModal={openModal} />
    </>
  );
}
