import Head from 'next/head';
import { useState } from 'react';
import { Inter } from 'next/font/google';
import { GasModal } from '@/features/gas';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [openModal, setOpenModal] = useState<boolean>(false);

  const handleClose = () => {
    setOpenModal(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="h-screen w-screen flex items-center justify-center bg-gray-100 text-white-500">
          <button
            onClick={() => setOpenModal(true)}
            className="bg-blue-500 hover:bg-blue-600 active:bg-blue-400 py-2 px-4 rounded-md shadow-xl"
          >
            Open
          </button>
        </div>
      </>
      <GasModal handleClose={handleClose} openModal={openModal} />
    </>
  );
}
